apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smb-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
      chart: csi-driver-smb
      targetRevision: v1.18.0
      helm:
        releaseName: csi-driver-smb
        values: |
          image:
            baseRepo: mcr.microsoft.com
            tag: v1.18.0
          node:
            updateStrategy:
              type: RollingUpdate
          controller:
            replicas: 1
    - repoURL: git@github.com:s33g/infra.git
      targetRevision: HEAD
      path: infrastructure/smb-csi
      directory:
        include: '{external-secret.yaml,storageclass.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
