apiVersion: v1
kind: Service
metadata:
  name: syslog-ng
  namespace: syslog-ng
  labels:
    app.kubernetes.io/name: syslog-ng
    app.kubernetes.io/managed-by: argocd
spec:
  type: LoadBalancer
  selector:
    app: syslog-ng
  ports:
  - name: syslog-udp
    port: 514
    targetPort: syslog-udp
    protocol: UDP
  - name: syslog-tcp
    port: 601
    targetPort: syslog-tcp
    protocol: TCP
  - name: syslog-tls
    port: 6514
    targetPort: syslog-tls
    protocol: TCP
