---

all:
  hosts:
    r2d2:
      ansible_connection: local
      ansible_host: localhost
      ansible_user: supervisor
    darth:
      ansible_host: darth.home
      ansible_user: seeg
    media:
      ansible_host: media.home
      ansible_user: seeg
    homeassistant:
      ansible_host: assistant.home
      ansible_user: seeg
