- name: Servers
  hosts: r2d2
  roles:
    - role: artis3n.tailscale.machine
      vars:
        verbose: true
        tailscale_authkey: "{{ secrets.tailscale.server.auth_client_secret }}"
        tailscale_tags:
          - "server"
        # Optionally, also include:
        tailscale_oauth_ephemeral: true
        tailscale_oauth_preauthorized: false
