apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: global-http-redirect
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - match: "PathPrefix(`/`)"
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: kube-system
      services:
        - name: traefik
          port: 80
