apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tdarr
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: tdarr.k3s.s33g.uk
    external-dns.alpha.kubernetes.io/target: 10.10.0.240
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tdarr.k3s.s33g.uk`)
      kind: Rule
      services:
        - name: tdarr
          port: 8265
  tls:
    secretName: wildcard-k3s-s33g-uk-tls
