apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: go-api
  namespace: go-api
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.k3s.s33g.uk
    external-dns.alpha.kubernetes.io/target: 10.10.0.240
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.k3s.s33g.uk`)
      kind: Rule
      services:
        - name: go-api
          port: 80
  tls:
    secretName: wildcard-k3s-s33g-uk-tls
