apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sabnzbd
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sabnzbd.k3s.s33g.uk
    external-dns.alpha.kubernetes.io/target: 10.10.0.240
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`sabnzbd.k3s.s33g.uk`)
    kind: Rule
    services:
    - name: sabnzbd
      port: 80
  tls:
    secretName: wildcard-k3s-s33g-uk-tls
