apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: plex.k3s.s33g.uk
    external-dns.alpha.kubernetes.io/target: 10.10.0.240
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`plex.k3s.s33g.uk`)
      kind: Rule
      services:
        - name: plex
          port: 32400
  tls:
    secretName: wildcard-k3s-s33g-uk-tls
