apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pinchflat
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pinchflat.k3s.s33g.uk
    external-dns.alpha.kubernetes.io/target: 10.10.0.240
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pinchflat.k3s.s33g.uk`)
      kind: Rule
      services:
        - name: pinchflat
          port: 8945
  tls:
    secretName: wildcard-k3s-s33g-uk-tls
