apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: deemix
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: deemix.k3s.s33g.uk
    external-dns.alpha.kubernetes.io/target: 10.10.0.240
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`deemix.k3s.s33g.uk`)
      kind: Rule
      services:
        - name: deemix
          port: 6595
  tls:
    secretName: wildcard-k3s-s33g-uk-tls
