apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unpackerr
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: unpackerr.k3s.s33g.uk
    external-dns.alpha.kubernetes.io/target: 10.10.0.240
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unpackerr.k3s.s33g.uk`)
      kind: Rule
      services:
        - name: unpackerr
          port: 5656
  tls:
    secretName: wildcard-k3s-s33g-uk-tls
