apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
  - repoURL: git@github.com:s33g/infra.git
    targetRevision: HEAD
    path: apps/go-api
    directory:
      include: '{deployment.yaml,service.yaml,redis.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: go-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
