# TODO: Fix the version of the roles
# Add renovate bot github action
---

roles:
  - name: geerlingguy.docker
collections:
  - name: vladgh.samba
  - name: community.docker
  - name: community.general
