apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: longhorn.k3s.s33g.uk
    external-dns.alpha.kubernetes.io/target: 10.10.0.240
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.k3s.s33g.uk`)
      kind: Rule
      middlewares:
        - name: authentik
          namespace: kube-system
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: wildcard-k3s-s33g-uk-tls
