apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gatus
  namespace: gatus
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gatus.k3s.s33g.uk
    external-dns.alpha.kubernetes.io/target: 10.10.0.240
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`gatus.k3s.s33g.uk`)
    kind: Rule
    services:
    - name: gatus
      port: 8080
  tls:
    secretName: wildcard-k3s-s33g-uk-tls
