apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-k3s-s33g-uk
  namespace: kube-system
  annotations:
    # Reflector will automatically copy the generated secret to these namespaces
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "gatus,argocd,monitoring,longhorn-system,uptime-kuma,default"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "gatus,argocd,monitoring,longhorn-system,uptime-kuma,default"
spec:
  secretName: wildcard-k3s-s33g-uk-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.k3s.s33g.uk"
    - "k3s.s33g.uk"
