ai_prometheus_scrape_configs:
  - job_name: nvidia-dcgm-exporter
    scrape_interval: 5s
    static_configs:
      - targets: ["{{ host }}:{{ ai_ports.dcgm_exporter }}"]
  - job_name: node_exporter
    scrape_interval: 30s
    static_configs:
      - targets: ["{{ host }}:{{ ai_ports.node_exporter }}"]
